import assert from "node:assert/strict";
import { test } from "node:test";
import {
  buildCommandPayload,
  decodeMessage,
  deriveMessageKey,
  encodeMessage,
  encodeTimestamp,
  hawkAuthorization,
  mqttConnectionParams,
  parseCommandResponse,
  parseDevices,
  resolveVacuumFromList,
} from "./roborock";

/**
 * Every hardcoded expected value below was generated by running the real
 * python-roborock library (the most actively maintained open-source
 * Roborock client), cloned directly into this session and installed with
 * pip, against the same inputs used here — not guessed at or copied from
 * documentation. See src/roborock.ts's top comment for the files read.
 * This is the only integration this session verified with byte-for-byte
 * parity against a real reference implementation rather than a mock.
 */

const LOCAL_KEY = "abcdef0123456789";
const TIMESTAMP = 1700000000;

test("encodeTimestamp: matches python-roborock's Utils.encode_timestamp", () => {
  assert.equal(encodeTimestamp(TIMESTAMP).toString("ascii"), "1030556f");
});

test("deriveMessageKey: matches python-roborock's key derivation", () => {
  assert.equal(deriveMessageKey(TIMESTAMP, LOCAL_KEY).toString("hex"), "c2da63e275f58710d4df6511b4865005");
});

test("buildCommandPayload: matches python-roborock's RequestMessage._as_payload", () => {
  const payload = buildCommandPayload({ id: 12345, method: "get_status", params: [] }, TIMESTAMP);
  assert.equal(payload.toString("utf-8"), `{"dps":{"101":"{\\"id\\":12345,\\"method\\":\\"get_status\\",\\"params\\":[]}"},"t":1700000000}`);
});

test("encodeMessage: matches python-roborock's MessageParser.build byte-for-byte", () => {
  const payload = buildCommandPayload({ id: 12345, method: "get_status", params: [] }, TIMESTAMP);
  const encoded = encodeMessage(
    { version: "1.0", seq: 500000, random: 50000, timestamp: TIMESTAMP, protocol: 101, payload },
    LOCAL_KEY,
  );
  assert.equal(
    encoded.toString("hex"),
    "312e300007a1200000c3506553f1000065006073df19dd993dee66dc1ea6ef6a8752e37fefac5ee00b2a799b85eb8ce2eccdd171224ab28e8db3f61a504968032a38970f5237a30aa60a540813879d3caabc35c118406e73261a7c73237b16fbca4bf5404eb4e6df432d4296717e122fa48b07f08ca7cb",
  );
});

test("decodeMessage + parseCommandResponse: decodes a real encrypted RPC_RESPONSE built by python-roborock", () => {
  const responseHex =
    "312e30000bde3100015b386553f17b00660080bbfbcf79b77af37b4f694c888cd3f71e07d46998aecf2734e006bf4deada9ad8118f4db04fbeb7c95b50f09538d1872a5440564b5b68e62a0ee28cdcc01cc3b29485cebcfac5b29bc9452e9f1eb0ece9abf1738d0cc0e23ec870c3a3ebfe2ff60dfe2f41b73ab9591f8e39dfa09e384522022a18808d6c727b3f78bcbd0fb0ffb2b9fb2e";
  const decoded = decodeMessage(Buffer.from(responseHex, "hex"), LOCAL_KEY);
  assert.equal(decoded.protocol, 102); // RPC_RESPONSE
  assert.equal(decoded.timestamp, 1700000123);

  const parsed = parseCommandResponse(decoded.payload);
  assert.equal(parsed.id, 12345);
  assert.deepEqual(parsed.result, [{ msg_ver: 2, state: 8, battery: 87, error_code: 0 }]);
  assert.equal(parsed.error, undefined);
});

test("encodeMessage -> decodeMessage round-trips locally", () => {
  const payload = buildCommandPayload({ id: 999, method: "app_start", params: [] }, TIMESTAMP);
  const encoded = encodeMessage(
    { version: "1.0", seq: 111, random: 222, timestamp: TIMESTAMP, protocol: 101, payload },
    LOCAL_KEY,
  );
  const decoded = decodeMessage(encoded, LOCAL_KEY);
  assert.equal(decoded.payload.toString("utf-8"), payload.toString("utf-8"));
  assert.equal(decoded.timestamp, TIMESTAMP);
  assert.equal(decoded.protocol, 101);
});

const RRIOT = {
  u: "user123",
  s: "secret456",
  h: "hmacsecret789",
  k: "sessionkeyABC",
  r: { a: "https://api.example.com", m: "ssl://mqtt-eu-3.roborock.com:8883" },
};

test("hawkAuthorization: matches python-roborock's _get_hawk_authentication", () => {
  const auth = hawkAuthorization(RRIOT, "/user/homes/12345", undefined, TIMESTAMP, "fixedNonce12");
  assert.equal(
    auth,
    `Hawk id="user123",s="secret456",ts="1700000000",nonce="fixedNonce12",mac="Zl7SkT3VehjIVgsreQM9qVYMMzxXh9eSX1fXW6kjhZw="`,
  );
});

test("mqttConnectionParams: matches python-roborock's create_mqtt_params", () => {
  const params = mqttConnectionParams(RRIOT);
  assert.deepEqual(params, {
    host: "mqtt-eu-3.roborock.com",
    port: 8883,
    tls: true,
    username: "24cb09c0",
    password: "5a75a54e9c76437c",
  });
});

test("mqttConnectionParams: a non-ssl scheme means no TLS", () => {
  const params = mqttConnectionParams({ ...RRIOT, r: { ...RRIOT.r, m: "tcp://mqtt.example.com:1883" } });
  assert.equal(params.tls, false);
  assert.equal(params.port, 1883);
});

test("parseDevices: keeps well-formed devices, drops malformed entries", () => {
  const raw = [
    { duid: "d1", name: "Living room", local_key: "key1", online: true },
    { duid: "d2", name: "Bedroom", local_key: "key2" }, // no online field, defaults to false
    { name: "missing duid", local_key: "key3" },
    { duid: "d3", name: "missing local_key" },
    null,
  ];
  const devices = parseDevices(raw);
  assert.deepEqual(devices, [
    { duid: "d1", name: "Living room", localKey: "key1", online: true },
    { duid: "d2", name: "Bedroom", localKey: "key2", online: false },
  ]);
});

test("resolveVacuumFromList: exact match wins, ambiguous match lists candidates", () => {
  const devices = [
    { duid: "d1", name: "Living room", localKey: "k1", online: true },
    { duid: "d2", name: "Living room 2", localKey: "k2", online: true },
  ];
  assert.equal(resolveVacuumFromList(devices, "living room").duid, "d1");
  assert.throws(() => resolveVacuumFromList(devices, "living"), /matches more than one vacuum/);
  assert.throws(() => resolveVacuumFromList(devices, "kitchen"), /no vacuum matching/);
});
